apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-service-v1
  labels:
    app: helloworld-service
data:
  HELLOSVC_KUBE_HOST: "0.0.0.0"
  HELLOSVC_MONITOR_HOST: "0.0.0.0"
  HELLOSVC_REST_HOST: "0.0.0.0"
